/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Prescription = IDL.Record({
  'notes' : IDL.Text,
  'consultationFee' : IDL.Nat,
  'medicines' : IDL.Vec(IDL.Text),
});
export const Patient = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'status' : IDL.Text,
  'prescription' : Prescription,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'gender' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addPatient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'deletePatient' : IDL.Func([IDL.Text], [], []),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getPatient' : IDL.Func([IDL.Text], [Patient], ['query']),
  'markAsPaid' : IDL.Func([IDL.Text], [], []),
  'updatePatientStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updatePrescription' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Prescription = IDL.Record({
    'notes' : IDL.Text,
    'consultationFee' : IDL.Nat,
    'medicines' : IDL.Vec(IDL.Text),
  });
  const Patient = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'status' : IDL.Text,
    'prescription' : Prescription,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'gender' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addPatient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'deletePatient' : IDL.Func([IDL.Text], [], []),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getPatient' : IDL.Func([IDL.Text], [Patient], ['query']),
    'markAsPaid' : IDL.Func([IDL.Text], [], []),
    'updatePatientStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updatePrescription' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };