/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Patient {
  'id' : string,
  'age' : bigint,
  'status' : string,
  'prescription' : Prescription,
  'name' : string,
  'createdAt' : bigint,
  'gender' : string,
  'phone' : string,
}
export interface Prescription {
  'notes' : string,
  'consultationFee' : bigint,
  'medicines' : Array<string>,
}
export interface _SERVICE {
  'addPatient' : ActorMethod<
    [string, string, string, bigint, string],
    undefined
  >,
  'deletePatient' : ActorMethod<[string], undefined>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getPatient' : ActorMethod<[string], Patient>,
  'markAsPaid' : ActorMethod<[string], undefined>,
  'updatePatientStatus' : ActorMethod<[string, string], undefined>,
  'updatePrescription' : ActorMethod<
    [string, Array<string>, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];